---

version: "3"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.7

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        links:
            - php
        ports:
            - 8000:8000

