---

version: "3"

services:
  php:
    image: bearstech/php:${PHP_VERSION}
    volumes:
      - ./www:/var/www/web

  nginx:
    build:
      context: .
      dockerfile: ./compose/Dockerfile.nginx
    links:
      - php
    ports:
      - 8000

  client:
    image: bearstech/debian:stretch
    volumes:
      - ./bin/goss:/usr/local/bin/goss
      - ./compose:/goss
    working_dir: /goss
    links:
      - nginx
    command: >
      goss -g http_test.yaml validate --max-concurrent 4 --format documentation

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf_fpm.conf:/etc/telegraf/telegraf.d/fpm.conf
      - ./bin/goss:/usr/local/bin/goss
      - .:/goss
    links:
      - php
    command: >
      telegraf --config /etc/telegraf/telegraf.d/fpm.conf --test
